### ISSUE TITLE
Manual capture is sometimes needed and sometimes not

### ISSUE THREAD

**Issue by christianz123** [SwedbankPay/swedbank-pay-woocommerce-checkout#117]
Hi
When the customer is doing the payment with invoice or credit, then a manual capture is needed within Woocommerce. This is done by pressing the capture button on the specific order. The order have status "Pending payment" until it has been manual captured.
When the customer is doing the payment with Swish, then the payment is captured immediately and no manual capture is needed. The order get status "Processing".

What is expected behaviour?
We are selling on the shelf products with same day delivery. So it would be nice if the payment is automatically captured.
See below fo the settings that are used.
![Screenshot 2022-02-03 at 19 50 32](https://user-images.githubusercontent.com/67435890/152409178-6050bae4-4438-45c2-9b5e-4b5cffc878b4.png)

Thanks

**Comment by aait** [comment]
Status is not "Pending Payment" but "On hold" as the official recommendation, please see https://woocommerce.com/document/managing-orders/#understanding-order-statuses-in-relation-to-payment-gateways 

However you can activate "Instant Capture" in the setting to bypass that step in the order flow.

**Comment by christianz123** [comment]
Thanks for the reply.
Instant capture sounds good but I have never managed to get it to work. As you see on the screenshoot in above post, instant capture is activated. I have tried with "Auto capture" enabled and disabled, no difference in behaviour. I still need to manually capture the payment.
What is the different between instant capture and auto capture. They sounds very similar :)

Thanks

**Comment by olegisk** [comment]
@christianz123 "Instant capture" doesn't work if  "Auto capture" is enabled

**Comment by aait** [comment]
@christianz123 please send us a case when Instant Capture does not work and we will troubleshoot it

**Comment by christianz123** [comment]
I have created an order with the payment method "credit".
The order status in WooCommerce is now "Pending payment".
The payment status in the payex portal is Authorized but not captured. Payee reference 294505xrgwfa, orderreference 294505.
![Screenshot 2022-02-10 at 21 59 17](https://user-images.githubusercontent.com/67435890/153495525-3e71ce24-12b0-4ae4-92f3-fbb0fc553039.png)

I also tried other payment methods and they worked fine. Credit is always behaving like this, invoice is inconsistent, sometimes ok, sometimes not ok.

Thanks

**Comment by aait** [comment]
@christianz123  Could you clarify what is Payment method "Credit"?

**Comment by christianz123** [comment]
See below for the "credit" method, "Kredit" in Swedish.

![Screenshot 2022-02-11 at 08 44 22](https://user-images.githubusercontent.com/67435890/153555056-f211923c-aa1c-4b8f-bca1-ad26e483c16c.png)

**Comment by aait** [comment]
Thank you, that is a new method that we have not implemented support for yet. We will inquire the API-team about this and keep you posted.

**Comment by olegisk** [comment]
@christianz123 It looks like webhooks are rejecting there. Can you disable "Enable IP checking of incoming callbacks" option and try again?
![Screenshot (19)](https://user-images.githubusercontent.com/871275/153571025-ab50855d-41db-4bef-8f1e-b189dd3244d9.png)

I think would be good to check your logs in WooCommerce > Status > Logs

**Comment by christianz123** [comment]
I have disabled the IP checking and it seems to be more stable.
Regarding "Credit", when do you think this will be supported? Week? Month?

Thanks

**Comment by olegisk** [comment]
> Regarding "Credit", when do you think this will be supported? Week? Month?
What do you mean?

**Comment by christianz123** [comment]
I was referring to this comment:
"Thank you, that is a new method that we have not implemented support for yet. We will inquire the API-team about this and keep you posted."

When do you think the API team will have added support for the "Credit" method? Week? Month?

Thanks

**Comment by aait** [comment]
Hi @christianz123  I have checked with the dev team. There is no official documentation for the "Credit" method in Swedbank Pay Checkout. Typically these methods should work out of the box but since you had problems with that method I wanted to investigate it. However, now it seems the problem was related to something else so you don't need to bother about it.

**Comment by christianz123** [comment]
Hi
I still have the "Credit" issue with status "Pending payment".
All other payment methods work fine, the order status is "Processing" and the payment is automatically captured.

Order 294515xitjlz, payment method Credit, order status Pending payment
Order 294514xcfsnr, payment method Invoice, order status status Processing

Thanks

**Comment by aait** [comment]
Please send logs for the time period around the event from WooCommerce > Status > Logs or give us access by mailing wp  credentials to info@aait.se
