### ISSUE TITLE
CancelURL sends customer to CompleteURL page

### ISSUE THREAD

**Issue by SimpleCryptoGuide** [SwedbankPay/swedbank-pay-woocommerce-checkout#142]
Hi!

We're having an issue where cancelling the payment on the Swedbank Pay Checkout page directs the customer to the "Thank you" page, as in the completed order URL. 

I can't seem to find any way to fix this myself, as it appears to be handled directly through an external javascript. 
Attaching pictures of the issue at hand. 

It should be noted that the order isn't processed as completed on the backend, so it is a front-end issue only.

Platform: Wordpress + Divi
Ecommerce platform: Woocommerce
Domain: https://www.greenbalance.se/

![Cancel](https://user-images.githubusercontent.com/124149603/216021708-706bd89e-17ec-4125-893d-1fadc3c6c35d.PNG)
![Tack](https://user-images.githubusercontent.com/124149603/216021904-7a94c2cb-0d40-482c-b18f-dcf1487059b9.PNG)

**Comment by aait** [comment]
@SimpleCryptoGuide we need to check the logs. Can we have site access? You can contact us with credentials info@aait.se

**Comment by SimpleCryptoGuide** [comment]
Adding a bit more information:

The process of pressing "Cancel order" also clears the customers basket entirely for whatever reason. 
Not sure if these issues are related to the frontend considering the order as "completed" or if this is a standalone issue.

**Comment by SimpleCryptoGuide** [comment]
Issue has now been fixed by @aait - functionality is back to normal
