### ISSUE TITLE
Error while placing order

### ISSUE THREAD

**Issue by seodrweb** [SwedbankPay/swedbank-pay-woocommerce-checkout#150]
We have a problem with not being able to place an order with Swedbank Pay. When you have entered your details in Swedbank Pay and go ahead and click "Place order", this error message appears:

"Input validation failed, error description in problems node!
PaymentOrder.Payer.ConsumerProfileRef: Both ConsumerProfileRef and PayerReference cannot be set at the same time."

Screenshot: https://i.postimg.cc/TRs2Yv44/Ska-rmavbild-2023-03-15-kl-13-04-07.png

PHP-version: 8.028
Wordpress: 6.1.1
Swedbank Pay 7.0
WooCoommerce: 7.4.1

**Comment by aait** [comment]
Please update your plugin, we released a fix for this yesterday.

**Comment by seodrweb** [comment]
Plugin updated, works now🙏 Thank you aait
