### ISSUE TITLE
Wordpress Fatal Error when editing or adding a new WooCommerce Coupon (marketing->coupon)

### ISSUE THREAD

**Issue by simenah** [SwedbankPay/swedbank-pay-woocommerce-checkout#155]
For some reason I get this when trying to add or edit Coupons. Any ideas?

Fatal error: Uncaught Error: Call to undefined method WP_Post::get_payment_method() in /..../wp-content/plugins/swedbank-pay-checkout/includes/class-wc-swedbank-admin.php:69 Stack trace: #0 /...../wp-includes/class-wp-hook.php(308): SwedbankPay\Checkout\WooCommerce\WC_Swedbank_Admin::add_meta_boxes() #1 /....../wp-includes/class-wp-hook.php(332): WP_Hook->apply_filters() #2 /....../wp-includes/plugin.php(517): WP_Hook->do_action() #3 /......./wp-admin/includes/meta-boxes.php(1599): do_action() #4 /......./wp-admin/edit-form-advanced.php(271): register_and_do_post_meta_boxes() #5 /..../wp-admin/post.php(206): require('/.....') #6 {main} thrown in /...../wp-content/plugins/swedbank-pay-checkout/includes/class-wc-swedbank-admin.php on line 69

**Comment by SweRog** [comment]
Hi

We just updated to the latest version and we got the same errors.  We had to take the shop down.

Need help urgent.

**Comment by aait** [comment]
Please send access details by email info@aait.se

**Comment by simenah** [comment]
Confirming fix - now working fine. Thank you!
