### ISSUE TITLE
Fatal error after updating to 7.1.0

### ISSUE THREAD

**Issue by seodrweb** [SwedbankPay/swedbank-pay-woocommerce-checkout#156]
After updating to 7.1.0 we can't view any orders.

WP 6.1.1

Warning: Attempt to read property "ID" on bool in /home/comfortz/cz.se/wp-content/plugins/woocommerce-services/classes/class-wc-connect-account-settings.php on line 32

Warning: Attempt to read property "display_name" on bool in /home/comfortz/cz.se/wp-content/plugins/woocommerce-services/classes/class-wc-connect-account-settings.php on line 44

Warning: Attempt to read property "user_login" on bool in /home/comfortz/cz.se/wp-content/plugins/woocommerce-services/classes/class-wc-connect-account-settings.php on line 45

Warning: Trying to access array offset on value of type bool in /home/comfortz/cz.se/wp-content/plugins/woocommerce-services/classes/class-wc-connect-account-settings.php on line 46

Warning: Trying to access array offset on value of type bool in /home/comfortz/cz.se/wp-content/plugins/woocommerce-services/classes/class-wc-connect-account-settings.php on line 47

**Comment by aait** [comment]
Please send access details by email info@aait.se
