### ISSUE TITLE
“API Exception. Please check logs”

### ISSUE THREAD

**Issue by asbjornu** [SwedbankPay/swedbank-pay-woocommerce-checkout#37]
@wickywills [writes](https://wordpress.org/support/topic/api-exception-please-check-logs/):

>When enabling test mode and placing an order in the checkout, I receive:
>
>```
>[Tue Sep 22 09:53:35 2020] [PID:3094199 EID:rHKcQ7IoUxI] [php7:notice:sapi_apache2.c(349)] [Host:mytestsite.com Client:176.10.244.110:0] order_number_new was called incorrectly. Order properties should not be accessed directly. Backtrace: do_action('wp_ajax_swedbank_pay_place_order'), WP_Hook->do_action, WP_Hook->apply_filters, WC_Gateway_Swedbank_Pay_Checkout->ajax_swedbank_pay_place_order, WC_Checkout->process_checkout, WC_Checkout->process_order_payment, WC_Gateway_Swedbank_Pay_Checkout->process_payment, SwedbankPay\\Core\\Core->initiatePaymentOrderPurchase, SwedbankPay\\Core\\Core->getOrder, SwedbankPay\\Core\\Adapter\\WC_Adapter->getOrderData, WC_Order->get_order_number, apply_filters('woocommerce_order_number'), WP_Hook->apply_filters, WC_EZOSC_Seq_Order_Number->get_order_number, WC_Abstract_Legacy_Order->__get, WC_Order->get_order_number, apply_filters('woocommerce_order_number'), WP_Hook->apply_filters, WC_EZOSC_Seq_Order_Number->get_order_number, WC_Abstract_Legacy_Order->__get, wc_doing_it_wrong. This message was added in version 3.0.
>```
>FYI this happens on an install with no other plugins (other than WooCommerce) enabled, and the Storefront theme activated. Plugins updated to latest versions.

**Comment by aait** [comment]
@asbjornu There's the problem isn't related to swedbank payments plugin, there's 3party problem.
You can see [this topic](https://wordpress.org/support/topic/plugin-not-compatible-with-woocommerce-v3/) wthere the same problem.

**Comment by aait** [comment]
They can disable "Sequential Order Numbers" to solve the problem

**Comment by wickywills** [comment]
"Sequential Order Numbers" is not even installed. As mentioned, "no other plugins" are enabled. Tested on a fresh install - same problem.

**Comment by aait** [comment]
@wickywills Please provide logs of fresh install
