### ISSUE TITLE
Hooks stops working

### ISSUE THREAD

**Issue by MattiasKallio** [SwedbankPay/swedbank-pay-woocommerce-checkout#77]
I'm using the actions 'woocommerce_order_status_changed' and 'woocommerce_order_status_completed' for som extra functionality, and when this plugin is activated they seem to be removed, because they are no longer being triggered.

Is there a way around this?

Mvh
//Mattias

**Comment by aait** [comment]
@MattiasKallio Our plugin doesn't remove all actions `woocommerce_order_status_changed`.
Only few:
```php
		remove_action(
			'woocommerce_order_status_changed',
			'\SwedbankPay\Payments\WooCommerce\WC_Swedbank_Plugin::order_status_changed',
			10
		);
		remove_action(
			'woocommerce_order_status_changed',
			'\SwedbankPay\Checkout\WooCommerce\WC_Swedbank_Plugin::order_status_changed',
			10
		);
```

**Comment by aait** [comment]
@MattiasKallio Actually, this action is disabled there https://github.com/SwedbankPay/swedbank-pay-woocommerce-checkout/blob/master/includes/class-wc-swedbank-plugin.php#L51
