### ISSUE TITLE
Subscriptions auto renewal

### ISSUE THREAD

**Issue by christianz123** [SwedbankPay/swedbank-pay-woocommerce-checkout#82]
Hi
I mixed up the payment plugin and the checkout plugin. This issue is related to the checkout plugin, not the payment plugin.

I am trying to setup the subscriptions functionality in Woocommerce
https://woocommerce.com/products/woocommerce-subscriptions/

The Swedbank Pay Checkout indicates that it shall support auto renewals. See attached screenshot.
![image](https://user-images.githubusercontent.com/67435890/118532934-cc1dd400-b747-11eb-9d46-d67bb27da7d1.png)

During the checkout process everything seems fine. Only one payment option is available (credit card). I assume that is because of the auto renewal functionality. That is OK.

The problem occurs during the first renewal. A new renewal order is created by the system but the payment status is pending. The customer need to manually do a new payment from the account page. During that payment process all payments options are available.

Expected behaviour is that the customer shall not manually do a new payment. This should be automatic.

I am using version 4.4.0 of the checkout plugin

Thanks

**Comment by christianz123** [comment]
When will these fixes be available in a public release?

**Comment by aait** [comment]
@christianz123 I think very soon
