### ISSUE TITLE
Subscriptions - API Exception: Invalid url

### ISSUE THREAD

**Issue by christianz123** [SwedbankPay/swedbank-pay-woocommerce-checkout#86]
Hi
I am trying to setup WC Subscriptions. I am using the latest version of WC Subscriptions and the Swedbank Pay Checkout plugin.

I have created a simple subscription product:
![Screenshot 2021-06-16 at 22 03 12](https://user-images.githubusercontent.com/67435890/122285216-bdfdd780-ceee-11eb-98e1-5d3e23cad8a5.png)

I have placed an order and paid with credit card. Credit card was the only available payment option, as expected.

When the subscription is renewed, the parent order get status OnHold.
![Screenshot 2021-06-16 at 22 06 30](https://user-images.githubusercontent.com/67435890/122285591-3a90b600-ceef-11eb-901b-d0b2160bc0ee.png)

And the new order get status "Pending payment".
![Screenshot 2021-06-16 at 22 07 54](https://user-images.githubusercontent.com/67435890/122285848-7b88ca80-ceef-11eb-80fc-9f0e6a092cfe.png)

Th expected behaviour is that the new payment shall be automatic completed. The customer shall not manually do a new payment.

The only thing I see in the log is:
![Screenshot 2021-06-16 at 22 17 49](https://user-images.githubusercontent.com/67435890/122286958-b808f600-cef0-11eb-837f-86ac63982f2e.png)

Thanks

**Comment by aait** [comment]
@christianz123 What does order 2908***** mean?
When order was renewed in On hold status then you must capture it manually. Or configure automatic capturing.
WC Subscriptions does suspend subscriptions with on-hold status.

In another hand, this can be if fatal error was occured during renewal. In this case we need for more details.

**Comment by christianz123** [comment]
"2908****" is the order ID of the created renewal order that belongs to the parent subscription order.

Automatic capturing is configured, see the settings from the plugin.
![Screenshot 2021-06-17 at 22 35 15](https://user-images.githubusercontent.com/67435890/122468978-b1e04b80-cfbc-11eb-8d6f-0a490c957013.png)

There is no way to do manual capture from either the parent subscription order or the generated renewal order. Normally if a manual capture is needed, there is a button on the specific order page to do a capture. 
In this case there is no button that can trigger a capture.

The first payment when doing the order is OK. Auto capture works fine. When the renewal order is created, then no capture is done.
I dont see any trace of the renewal order in the payex portal. I see the first payment in the portal but not the renewal.

Any ideas?

**Comment by aait** [comment]
@christianz123 hmm. It looks weird. Could you contact us info@aait.se please to look this site deeper?
